#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Keras_Preprocessing
Version  : 1.0.6
Release  : 16
URL      : https://files.pythonhosted.org/packages/6e/bd/1555135d8a54c09cf8eccd4755c3361d043e53f74aeda29f89c0d94fe8b6/Keras_Preprocessing-1.0.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/6e/bd/1555135d8a54c09cf8eccd4755c3361d043e53f74aeda29f89c0d94fe8b6/Keras_Preprocessing-1.0.6.tar.gz
Summary  : Easy data preprocessing and data augmentation for deep learning models
Group    : Development/Tools
License  : MIT
Requires: Keras_Preprocessing-python = %{version}-%{release}
Requires: Keras_Preprocessing-python3 = %{version}-%{release}
Requires: Pillow
Requires: numpy
Requires: scipy
Requires: six
BuildRequires : Keras
BuildRequires : buildreq-distutils3
BuildRequires : numpy
BuildRequires : six

%description
# Keras Preprocessing
[![Build Status](https://travis-ci.org/keras-team/keras-preprocessing.svg?branch=master)](https://travis-ci.org/keras-team/keras-preprocessing)

%package python
Summary: python components for the Keras_Preprocessing package.
Group: Default
Requires: Keras_Preprocessing-python3 = %{version}-%{release}
Provides: keras_preprocessing-python

%description python
python components for the Keras_Preprocessing package.


%package python3
Summary: python3 components for the Keras_Preprocessing package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Keras_Preprocessing package.


%prep
%setup -q -n Keras_Preprocessing-1.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548817253
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
